#moduledir '/opt/puppet'
mod 'puppetlabs-firewall', '1.9.0'
mod 'dhoppe-fail2ban', '1.3.4'
mod 'herculesteam-augeasproviders', '2.1.3'
mod 'puppetlabs-ruby', '1.0.0'
mod 'puppetlabs-apt --version 4.1.0'
mod 'maestrodev-rvm', '1.13.1'
mod 'gajdaw-puppet', '0.1.7'
mod 'puppetlabs-apache', '1.11.0'
mod 'puppetlabs-stdlib', '4.17.1'
mod 'puppetlabs-passenger', '0.4.1'